# CoFound.ai Workflow Definitions
# This file contains predefined workflows for the multi-agent system

workflows:
  - id: "develop_app"
    name: "Software Development Workflow"
    description: "Standard workflow for developing a software application"
    initiator: "Planner"
    initial_prompt: "Create a development plan for the project"
    langgraph:
      states:
        - name: "Planning"
          description: "Project planning and task breakdown"
          agent: "Planner"
        - name: "Architecture"
          description: "System architecture design"
          agent: "Architect"
        - name: "Development"
          description: "Code implementation"
          agent: "Developer"
        - name: "Testing"
          description: "Code testing and quality assurance"
          agent: "Tester"
        - name: "Review"
          description: "Code review and improvements"
          agent: "Reviewer"
        - name: "Documentation"
          description: "Project documentation"
          agent: "Documentor"
      transitions:
        - from: "Planning"
          to: "Architecture"
        - from: "Architecture"
          to: "Development"
        - from: "Development"
          to: "Testing"
        - from: "Testing"
          to: "Review"
        - from: "Review"
          to: "Documentation"
        - from: "Documentation"
          to: null
    phases:
      - name: "Planning"
        description: "Project planning and task breakdown"
        agent: "Planner"
        next: "Architecture"
      - name: "Architecture"
        description: "System architecture design"
        agent: "Architect"
        next: "Development"
      - name: "Development"
        description: "Code implementation"
        agent: "Developer"
        next: "Testing"
      - name: "Testing"
        description: "Code testing and quality assurance"
        agent: "Tester"
        next: "Review"
      - name: "Review"
        description: "Code review and improvements"
        agent: "Reviewer"
        next: "Documentation"
      - name: "Documentation"
        description: "Project documentation"
        agent: "Documentor"
        next: null

  - id: "prototype"
    name: "Rapid Prototype Workflow"
    description: "Streamlined workflow for creating a quick prototype"
    initiator: "Planner"
    initial_prompt: "Create a minimal prototype plan"
    langgraph:
      states:
        - name: "Planning"
          description: "Minimal planning for prototype"
          agent: "Planner"
        - name: "Development"
          description: "Rapid prototype implementation"
          agent: "Developer"
        - name: "Testing"
          description: "Basic testing of prototype"
          agent: "Tester"
      transitions:
        - from: "Planning"
          to: "Development"
        - from: "Development"
          to: "Testing"
        - from: "Testing"
          to: null
    phases:
      - name: "Planning"
        description: "Minimal planning for prototype"
        agent: "Planner"
        next: "Development"
      - name: "Development"
        description: "Rapid prototype implementation"
        agent: "Developer"
        next: "Testing"
      - name: "Testing"
        description: "Basic testing of prototype"
        agent: "Tester"
        next: null

  - id: "code_review"
    name: "Code Review Workflow"
    description: "Workflow for reviewing existing code"
    initiator: "Reviewer"
    initial_prompt: "Analyze and review the provided code"
    langgraph:
      states:
        - name: "Analysis"
          description: "Static analysis of code"
          agent: "Reviewer"
        - name: "Feedback"
          description: "Generate improvement feedback"
          agent: "Reviewer"
        - name: "Improvement"
          description: "Implement suggested improvements"
          agent: "Developer"
      transitions:
        - from: "Analysis"
          to: "Feedback"
        - from: "Feedback"
          to: "Improvement"
        - from: "Improvement"
          to: null
    phases:
      - name: "Analysis"
        description: "Static analysis of code"
        agent: "Reviewer"
        next: "Feedback"
      - name: "Feedback"
        description: "Generate improvement feedback"
        agent: "Reviewer"
        next: "Improvement"
      - name: "Improvement"
        description: "Implement suggested improvements"
        agent: "Developer"
        next: null 